title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
          buttons:
            type: structure
            label: Buttons
            fields:
              text:
                type: text
                label: Button Text
              link:
                type: link
                label: Button Link
              style:
                type: select
                label: Button Style
                options:
                  primary: Primary
                  secondary: Secondary
                  outline: Outline
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

